import math
from typing import List, Dict, Any
from app.schemas.research import (
    DensityComputationRequest,
    DensityStratificationResponse,
    QueryGeneratorRequest,
    QueryGeneratorResponse
)

class ResearchEngine:
    """
    Phase 19: Researcher & Advanced Scientific Workbench Engine
    Calculates equation of state approximations (TEOS-10 potential density, sound speed,
    Brunt-Vaisala buoyancy frequency N^2, and barrier layer thickness), and generates code queries.
    """

    def compute_density_stratification(self, req: DensityComputationRequest) -> DensityStratificationResponse:
        depths = req.depth_m
        temps = req.temperature_c
        sals = req.salinity_psu
        n = min(len(depths), len(temps), len(sals))

        if n < 2:
            # Fallback mock profile if fewer than 2 points provided
            depths = [0, 10, 25, 50, 75, 100, 150, 200, 300, 500, 800, 1000]
            temps = [28.9, 28.85, 28.5, 27.2, 24.1, 21.0, 16.5, 14.2, 12.1, 10.1, 8.2, 6.5]
            sals = [33.2, 33.22, 33.45, 34.1, 34.8, 35.0, 35.1, 35.05, 35.02, 35.0, 34.9, 34.8]
            n = len(depths)

        g = 9.81  # m/s^2
        rho0 = 1025.0  # reference density kg/m^3

        potential_density: List[float] = []
        sigma_theta: List[float] = []
        sound_speeds: List[float] = []

        # 1. Simplified UNESCO / TEOS-10 seawater equation of state
        for i in range(n):
            t = temps[i]
            s = sals[i]
            z = depths[i]
            p = z * 1.005  # dbar

            # UNESCO simplified density formula
            rho = (
                999.842594 +
                6.793952e-2 * t -
                9.095290e-3 * (t ** 2) +
                1.001685e-4 * (t ** 3) +
                (0.824493 - 4.0899e-3 * t + 7.6438e-5 * (t ** 2)) * s +
                (-5.72466e-3 + 1.0227e-4 * t) * (s ** 1.5) +
                4.8314e-4 * (s ** 2)
            )
            # Pressure compressibility effect
            rho_p = rho + (p * 4.5e-3)

            potential_density.append(round(rho_p, 3))
            sigma_theta.append(round(rho - 1000.0, 3))

            # Chen-Millero Sound Speed in Seawater (m/s)
            c = 1449.2 + 4.6 * t - 0.055 * (t ** 2) + 0.00029 * (t ** 3) + (1.34 - 0.010 * t) * (s - 35.0) + 0.016 * z
            sound_speeds.append(round(c, 2))

        # 2. Brunt-Väisälä Buoyancy Frequency Squared N^2 = -(g / rho0) * (d_rho / d_z)
        n2_values: List[float] = [0.0]
        max_n2 = -1.0
        max_n2_depth = 0.0

        for i in range(1, n):
            dz = depths[i] - depths[i - 1]
            if dz > 0:
                drho = potential_density[i] - potential_density[i - 1]
                n2 = (g / rho0) * (drho / dz)
                n2 = max(0.0, n2)  # Stability criterion
            else:
                n2 = 0.0

            n2_values.append(round(n2, 7))
            if n2 > max_n2:
                max_n2 = n2
                max_n2_depth = (depths[i] + depths[i - 1]) / 2.0

        # 3. Mixed Layer Depth (MLD) based on delta sigma_theta = 0.125 kg/m^3 criterion
        surface_sigma = sigma_theta[0]
        mld = 35.0
        for i in range(1, n):
            if sigma_theta[i] - surface_sigma >= 0.125:
                mld = depths[i]
                break

        # 4. Isothermal Layer Depth (ILD) based on delta T = 0.2 °C criterion
        surface_temp = temps[0]
        ild = 58.0
        for i in range(1, n):
            if surface_temp - temps[i] >= 0.2:
                ild = depths[i]
                break

        # 5. Barrier Layer Thickness (BLT = max(0, ILD - MLD))
        blt = max(0.0, ild - mld)

        return DensityStratificationResponse(
            depth_m=depths,
            potential_density_kg_m3=potential_density,
            sigma_theta_kg_m3=sigma_theta,
            buoyancy_frequency_squared_n2=n2_values,
            sound_speed_m_s=sound_speeds,
            mixed_layer_depth_m=round(mld, 1),
            isothermal_layer_depth_m=round(ild, 1),
            barrier_layer_thickness_m=round(blt, 1),
            pycnocline_depth_m=round(max_n2_depth, 1),
            maximum_stability_n2=round(max_n2, 6),
            maximum_stability_depth_m=round(max_n2_depth, 1)
        )

    def generate_research_query(self, req: QueryGeneratorRequest) -> QueryGeneratorResponse:
        qtype = req.query_type.lower()

        if qtype == "erddap_python":
            code = f"""# ==============================================================================
# INCOIS ERDDAP Automated In-Situ Extraction Script
# Generated by SIH2026 Ocean Data Intelligence Platform
# ==============================================================================
import pandas as pd
from erddapy import ERDDAP

e = ERDDAP(
    server="https://erddap.incois.gov.in/erddap",
    protocol="tabledap",
    response="csv"
)

e.dataset_id = "Indian_ARGO_Floats"
e.variables = ["PLATFORM_NUMBER", "time", "latitude", "longitude", "PRES", "{req.variable.upper()}", "PSAL"]
e.constraints = {{
    "time>=": "{req.time_range[0]}T00:00:00Z",
    "time<=": "{req.time_range[1]}T23:59:59Z",
    "PRES>=": {req.depth_range[0]},
    "PRES<=": {req.depth_range[1]},
    "latitude>=": {req.lat_range[0]},
    "latitude<=": {req.lat_range[1]},
    "longitude>=": {req.lon_range[0]},
    "longitude<=": {req.lon_range[1]}
}}

df = e.to_pandas()
print(f"Harvested {{len(df)}} in-situ profiles across Indian Ocean bounds.")
print(df.head())
"""
            url = f"https://erddap.incois.gov.in/erddap/tabledap/Indian_ARGO_Floats.html"
            instructions = "Install `pip install erddapy pandas` and run the script in your Python / Jupyter scientific environment."

        elif qtype == "xarray_hycom":
            code = f"""# ==============================================================================
# NOAA / HYCOM Global 1/12° OpenDAP Slicing Script
# ==============================================================================
import xarray as xr
import matplotlib.pyplot as plt

opendap_url = "https://tds.hycom.org/thredds/dodsC/GLBy0.08/expt_93.0"
ds = xr.open_dataset(opendap_url)

# Slice spatial and vertical bounding box
subset = ds['water_{req.variable}'].sel(
    lat=slice({req.lat_range[0]}, {req.lat_range[1]}),
    lon=slice({req.lon_range[0]}, {req.lon_range[1]}),
    depth=slice({req.depth_range[0]}, {req.depth_range[1]}),
    time=slice("{req.time_range[0]}", "{req.time_range[1]}")
)

print("Subset Dimensions:", subset.shape)
subset.mean(dim='time').isel(depth=0).plot(cmap='turbo')
plt.title("HYCOM {req.variable.capitalize()} Field")
plt.show()
"""
            url = "https://tds.hycom.org/thredds/dodsC/GLBy0.08/expt_93.0.html"
            instructions = "Install `pip install xarray netcdf4 matplotlib` for zero-download remote OPeNDAP slicing."

        else:
            code = f"""% MATLAB CTD & Hydrographic Stratification Loader
url = 'https://erddap.incois.gov.in/erddap/tabledap/Indian_ARGO_Floats.csv?latitude,longitude,PRES,TEMP,PSAL';
data = webread(url);
disp('Successfully imported INCOIS Argo hydrographic profiles.');
"""
            url = "https://incois.gov.in"
            instructions = "Execute directly within MATLAB R2022b+ Command Window."

        return QueryGeneratorResponse(
            language="Python / xarray" if "python" in qtype or "xarray" in qtype else "MATLAB",
            code_snippet=code.strip(),
            direct_url=url,
            instructions=instructions
        )

research_engine = ResearchEngine()
